name: CI

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch: # This line allows you to run the workflow manually from the Actions tab

jobs:
  stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Mark and close stale pull requests
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 1
          days-before-close: 1
          stale-pr-message: 'This PR has been inactive for a day. It will be closed if no further activity occurs.'
          close-pr-message: 'Closing this PR due to inactivity.'
