# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Mark and close stale pull requests
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 1
          days-before-close: 1
          stale-pr-message: 'This PR has been inactive for a day. It will be closed if no further activity occurs.'
          close-pr-message: 'Closing this PR due to inactivity.'
